name: The release watcher

on:
    push:
        branches:
            - main

    schedule:
        - cron: '0 9 * * MON'

    workflow_dispatch:

jobs:
    watch:
        runs-on: ubuntu-latest
        steps:
            - name: Print event name 
              run: echo "The event that triggered this run is ${{github.event_name}}"

            - name: Print current date and time
              run: |
                echo "The current date and time is $(date)"

            - name: final message
              run: echo "Release watch complete"